export const locationsData = [

        {
            "nombre": "Plaça del Prado",
            "descripcion": "Plaça sense trànsit rodat, que connecta amb el passeig Germanies, on els vianants tenen prioritat. L'espai compta amb un parc amb gronxadors i tobogans i una esplanada per al joc lliure.",
            "modalidad": "Presencial",
            "acceso": "Gratuït",
            "condiciones": "Lliure",
            "direccion": [38.964595002456456, -0.18292777417730785],
            "web": null,
            "telefono": null,
            "email": null,
            "barrio": "Raval",
            "establecimiento": "Sí",
            "finalidad": ["Prevenció", "Promoció"],
            "temas": ["Activitat física"],
            "grupo_de_edad": "Totes les edats"
        },
        {
            "nombre": "Plaça Tirant",
            "descripcion": "Plaça sense trànsit rodat, ubicada al costat del riu Serpis, on els vianants tenen prioritat. Presenta diferents espais per a que la xicalla realitze zctivitat física. Compta amb un parc infantil (gronxadors i tobogans), una esplanada per al joc lluire, una zona amb ombra i bancs i una escultura en forma de G que es empleada com a tobogan.",
            "modalidad": "Presencial",
            "acceso": "Gratuït",
            "condiciones": "Lliure",
            "direccion": [38.964618212698106, -0.17823563185007002],
            "web": null,
            "telefono": null,
            "email": null,
            "barrio": "Raval",
            "establecimiento": "Sí",
            "finalidad": ["Prevenció", "Promoció"],
            "temas": ["Activitat física"],
            "grupo_de_edad": "Totes les edats"
        },
        {
            "nombre": "Parc infantil Jardins de la Marquesa",
            "descripcion": "Parc infantil ubicat dins dels jardins de la Marquesa, amb diferents estructures per al joc. Aquest parc compta amb banys públics, banc i zones de ombra.",
            "modalidad": "Presencial",
            "acceso": "Gratuït",
            "condiciones": "Lliure",
            "direccion": [38.96604837497469, -0.18184937497575188],
            "web": null,
            "telefono": null,
            "email": null,
            "barrio": "Raval",
            "establecimiento": "Sí",
            "finalidad": ["Prevenció", "Promoció"],
            "temas": ["Activitat física"],
            "grupo_de_edad": "Xicoteta infància (0-3 anys)"
        },
        {
            "nombre": "Plaça Sant Josep",
            "descripcion": "Plaça diàfana que compta amb un tobogà i una amplia esplanada per al joc lliure. A més té bancs i zones d'ombra.",
            "modalidad": "Presencial",
            "acceso": "Gratuït",
            "condiciones": "Lliure",
            "direccion": [38.9640136877357, -0.18118407417729082],
            "web": null,
            "telefono": null,
            "email": null,
            "barrio": "Raval",
            "establecimiento": "Sí",
            "finalidad": ["Prevenció", "Promoció"],
            "temas": ["Activitat física"],
            "grupo_de_edad": "Xicoteta infància (0-3 anys)"
        },
        {
            "nombre": "Parc de la Fira",
            "descripcion": "Parc infantojuvenil emplaçat en una zona verda, amb arbres i gespa. Compta amb una tirolina i altres estrucures per al joc, així com espai per al joc lliure.",
            "modalidad": "Presencial",
            "acceso": "Gratuït",
            "condiciones": "Lliure",
            "direccion": [38.964839495292175, -0.17532612977753487],
            "web": null,
            "telefono": null,
            "email": null,
            "barrio": "Raval",
            "establecimiento": "Sí",
            "finalidad": ["Prevenció", "Promoció"],
            "temas": ["Activitat física"],
            "grupo_de_edad": "Xicoteta infància (0-3 anys)"
        },
        {
            "nombre": "Parc Àusias March",
            "descripcion": "Parc emplaçat en un espai verd que compta amb zona infantil i un parc biosaludable. Sol ser gastat per joves, famílies i persones que practique esport.",
            "modalidad": "Presencial",
            "acceso": "Gratuït",
            "condiciones": "Lliure",
            "direccion": [38.96459877927735, -0.17651842284574792],
            "web": null,
            "telefono": null,
            "email": null,
            "barrio": "Raval",
            "establecimiento": "Sí",
            "finalidad": ["Prevenció", "Promoció"],
            "temas": ["Activitat física"],
            "grupo_de_edad": "Totes les edats"
        },
    {
        "nombre": "Plaça del Molí",
        "descripcion": "Plaça diàfana que compta amb bancs i zones d'ombra.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.96288982809333, -0.18010470301378756],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Xicoteta infància (0-3 anys)"
    },
    {
        "nombre": "Pati del CEIP Sant Francesc de Borja",
        "descripcion": "Pista deportiva per a jugar a diversos esports. Requereix de reserva prèvia per poder emprar-la en horari extra escolar.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Requereix reserva d'espai",
        "direccion": [38.96269051326399, -0.18297650486870418],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Xicoteta infància (0-3 anys)"
    },
    {
        "nombre": "Pont Vell d'Oliva",
        "descripcion": "Pont peatonal, ubicat prop del parc de la fira, idoni per a passejar.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.9612884026398, -0.17872481835951215],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Carrer Algepseria",
        "descripcion": "Carrer peatonal, que compta amb ombra, idoni per a passejar. A més conecta amb diferents parcs i places de la zona (Plaça del Moli i Plaça de Sant Josep)",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.962218403035116, -0.18099037417741787],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Carrer Sant Salvador",
        "descripcion": "Carrer peatonal, que compta amb ombra, idoni per a passejar. Paralel al carrer Algepseria, també conecta amb diferents parcs i places de la zona (plaça del Moli i plaça de Sant Josep)",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.962909116723225, -0.18139138952297582],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Centre Social del Raval",
        "descripcion": "Centre municipal en el qual s'oferten, entre altres, activitats vinculades a l'activitat física, com ioga i pilates.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Requereix inscripció",
        "direccion": [38.96254226362477, -0.18051772102491714],
        "web": "https://www.gandia.es/aytg/Web_php/index.php?contenido=subapartados_woden&id_boto=139&contenido=subapartados_woden&id_boto=139",
        "telefono": "962959625",
        "email": "informadorraval@gandia.org",
        "barrio": "Raval",
        "establecimiento": "No",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Parc de Petanca Vora Riu",
        "descripcion": "Parc de petanca situat en una zona verda amb ombra i bancs. Creat pel Club de petanca i l'Associació veïnal del Raval. És utilitzat qüotidianament pel veïnat.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.96254226362477, -0.18051772102491714],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Parc de Petanca de l'Alqueria Martorell",
        "descripcion": "Parc de petanca ubicat en un parc amb zona verda, bancs i arbrada, així com una zona de joc infantil.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.95661342096716, -0.18527059593035666],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Parc infantil del carrer Safor",
        "descripcion": "Parc que compta amb una zona de joc infantil, una esplanada de terra, bancs i ombra. Molt emprat pel veïnat donat que és un espai obert on hi ha poc transit rodat.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.95661342096716, -0.18527059593035666],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Xicoteta infància (0-3 anys)"
    },
    {
        "nombre": "Pavelló del Raval- Benipeixar",
        "descripcion": "Espai municipal tancat per a la pràctica d'activitat física i esports en grup. L'utilitzen entitats de la ciutat com clubs esportius i associacions. Compta amb sales grans i cobertes, útils per a fer ioga, pilates, etc.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Requereix reserva d'espai",
        "direccion": [38.96024734905013, -0.18399061431498764],
        "web": "https://www.gandia.es/aytg/Web_php/index.php?contenido=subapartados_woden&id_boto=404#primero",
        "telefono": "962 95 96 96",
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Pistas de petanca del Camí del Real",
        "descripcion": "Parc de petanca situat en una zona verda amb ombra i bancs i una zona on es pot jugar amb la infància",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.96072326204038, -0.18503160349254194],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Ruta Pont de Ferro",
        "descripcion": "Camí que rodeja Gandia emprat normalment per a caminar, córrer o anar en bici. Té diversos punts d'accés. Connecta el barri amb el centre de la ciutat i altes barris.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.95815160323389, -0.1817673003166369],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Anella verda - Riu Serpis",
        "descripcion": "Camí que rodeja Gandia emprat normalment per a caminar, córrer o anar en bici. Té diversos punts d'accés i està molt bé connectat amb el barri, permitent arribar al centre de la ciutat.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.96575452456064, -0.17940502306790854],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Parc de Cal·listènia",
        "descripcion": "Instal·lació esportiva a l'aire lliure que té com a avantatge la practicar esport al carrer. Encara que majoritàriament la Cal·listènia és practicada per joves, que volen millorar la seua resistència física i desenvolupament muscular, també és adequada per a persones majors que necessiten realitzar exercici de baix impacte per a millorar la seua agilitat, coordinació i flexibilitat. A més, ajuda al foment de les relacions personals.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.95750389945409, -0.17047863140796404],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Adolescència (12-18 anys)"
    },
    {
        "nombre": "Carril bici",
        "descripcion": "Carril bici del barri que connecta diversos punts del barri.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.95750389945409, -0.17047863140796404],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Raval",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Avinguda de la Mar",
        "descripcion": "Zona de passeig que uneix el barri de Corea, a Gandia, amb el del Grau de Gandia. És una zona àmplia, per la qual moltes persones passegen. Està coberta d'arbres que li donen ombra i també té en tot el seu recorregut bancs per a poder asseure's i descansar.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.979658895228326, -0.17098800292787353],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Carril bici",
        "descripcion": "Carril que connecta Gandia (situat al costat del Poliesportiu Municipal) amb Oliva, i tots els pobles que hi ha entre tots dos municipis: Bellreguard, Miramar, l'Alqueria de la Comtessa, Piles, entre altres. A més, aquest carril permet arribar a l'Hospital Francisco de Borja caminant. Molt utilitzat per a practicar diferents tipus d'esport com caminar, córrer, anar amb bici, en patinet... o desplaçar-se al treball en transport de zero emissions.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.979658895228326, -0.17098800292787353],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Camí a l'Alqueria del Duc (Marjal)",
        "descripcion": "Camí que connecta el barri de Corea amb la Marjal de Gandia, situada al costat de l'Alqueria del Duc del segle XVI. Es tracta d'una preciosa reserva de fauna i flora d'importantíssim valor ecològic i botànic. És un espai en el qual es pot practicar esport, ja que compta amb moltes zones verdes, així com caminar, córrer o anar amb bici pels seus camins. També és un espai excel·lent per a desconnectar i passar el dia.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": null,
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Parc de l'Estació",
        "descripcion": "El parc, situant fora de l'estació de Renfe rodalia, compta amb diverses parts. La part de l'antiga estació convertida en biblioteca municipal de barri, una zona de bancs, pistes, un parc infantil, i una esplanada àmplia coberta per arbres que he fan ombra. Normalment sol haver-hi grups de persones majors jugant a la petanca.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.97102346283764, -0.1793181030134654],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Parc de Petanca de l'Estació",
        "descripcion": "El parc de l'Estació compta amb una esplanada on la gent juga freqüentment a la petanca, rodejat d'arbres, amb ombra i bancs.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.97046079540581, -0.17839647337915476],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Poliesportiu Municipal",
        "descripcion": "El poliesportiu compta diversos espais per a realitzar esport: piscina coberta i convertible, pavelló d'usos múltiples, galeria de tir, gimnàs amb tatami, barra de ballet, sala d'aeròbic, pavelló d'halterofília, pistes d'atletisme, pista de tennis i de voleibol descobertes, pistes de básquet, pista polivalent, pista de patinatge, estadi de futbol Guillermo *Olagüe, camp de *rudby i futbol 8. Per a emprar les instal·lacions esportives de piscina, pista d'atletisme, tennis, pàdel, bàsquet, futbol, frontó i agoraespace per lliure, s'ha de pagar una quota d'usuari diaria, semestral o anual. Els preus varien en funció del tipus d'usuari: individual, famílies, menor de 18 anys, persones adultes o jubilades (informació en web i oficina). El poliesportiu ofereix cursos de natació, tennis i pàdel, en diferents horaris, que es paguen a part de la quota d'usuari. Més informació en les oficines del poliesportiu situada en l'avinguda dels esports 4, Gandia. Horari: L a J de 8.30 a 14:30h i de 17 a 19h; i V de 8.30 a 14h.",
        "modalidad": "Presencial",
        "acceso": "No Gratuït",
        "condiciones": "Requereix inscripció",
        "direccion": [38.97002952422198, -0.17411693184992696],
        "web": "https://www.gandia.es/aytg/Web_php/index.php?contenido=subapartados_woden&id_boto=404#primero",
        "telefono": "96 295 96 96",
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Consell Jove",
        "descripcion": "El Consell Jove és òrgan que representa al conjunt juvenil de Gandia, format per diverses entitats amb diferents objectius com és el foment d'activitats esportives, d'oci, etc. Durant tot l'any s'organitzen diverses activitats d'esport que es poden consultar a la web, cridant o acudint a l'espai físic.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Requereix inscripció",
        "direccion": [38.97437196699643, -0.17282998766764962],
        "web": "www.cjg.es; /www.instagram.com/consellgandia/",
        "telefono": "96 295 12 00",
        "email": "jovesgandia@cjg.es",
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Actividad física"],
        "grupo_de_edad": "Adolescència (12-18 anys)"
    },
    {
        "nombre": "Parc de Cal·listènia",
        "descripcion": "Nova instal·lació esportiva a l'aire lliure que té com a avantatge la practicar esport al carrer. Encara que majoritàriament la cal·listènia és practicada per joves, que volen millorar la seua resistència física i desenvolupament muscular, també és adequada per a persones majors que necessiten realitzar exercici de baix impacte per a millorar la seua agilitat, coordinació i flexibilitat. A més, ajuda al foment de les relacions personals.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.97485690764287, -0.17372282595843055],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Adolescència (12-18 anys)"
    },
    {
        "nombre": "Parc biosaludable",
        "descripcion": "Equipament situat al parc de l'Est, a l'ombra de molts arbres. Aquest connecta amb el carril bici que uneix Gandia i Grau. Aquest equipament permet que les persones facen exercici a l'aire lliure, en qualsevol moment del dia i de manera gratuïta.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.974672, -0.173731],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Adolescencia (12-18 años)"
    },
    {
        "nombre": "Parc de l'Est",
        "descripcion": "Ampli espai que compta amb moltes zones verdes i d'ombra on es practica exercici físic. A més compta amb un parc infantil, fonts, bancs, un espai biosaludable i just al costat comença el carril bici cap al grau de Gandia.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.97476294517525, -0.1741885265171403],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Centre de Majors de Corea",
        "descripcion": "Centre municipal en el qual es realitzen diverses activitats per a la gent gran de Gandia, entre elles, gimnàstica, balls de saló, ioga, sevillanes... És un recurs gratuït però per a poder accedir s'ha de realitzar la matrícula al setembre. Es pot acudir al centre o telefonar per a més informació.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Requereix inscripció",
        "direccion": [38.9742825853415, -0.17521010301333265],
        "web": "https://www.gandia.es/aytg/web_php/index.php?contenido=subapartados_woden&id_boto=51",
        "telefono": "96 295 96 68 640 566 007",
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Persones majors (+65 anys)"
    },
    {
        "nombre": "Mou-te",
        "descripcion": "Recurs d'activitat física de caràcter grupal i acompanyada per personal professional que presta serveis socials de l'Ajuntament de Gandia.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Requereix inscripció",
        "direccion": [38.97114851677655, -0.18477915647019286],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Joventut (18-35 anys)"
    },
    {
        "nombre": "El Jardinet",
        "descripcion": "El Jardinet està situat en la plaça de l'Exèrcit Espanyol, prop de la seu de la Guàrdia Civil i a cinc minuts de l'estació de tren. Compta amb un gran parc infantil, un carril bici, bancs, fonts i ombres. Està al costat de l'eixida d'un col·legi públic amb la qual cosa és molt usat pels xiquets i xiquetes i les seues famílies.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.97114851677655, -0.18477915647019286],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Xicoteta infància (0-3 anys)"
    },
    {
        "nombre": "Carril bici Gandia- Grau",
        "descripcion": "Zona molt ocupada per les persones del municipi per a caminar, patinar, córrer, desplaçar-se, etc. en el 2023 s'ha modernitzat tant el bici, com les zones per als vianants, i s'ha inclòs més arbrat, bancs i parades d'autobús.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.97114851677655, -0.18477915647019286],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Anella verda - Riu Serpis",
        "descripcion": "Camí que rodeja Gandia emprat normalment per a caminar, córrer o anar en bici. Té diversos punts d'accés. Connecta el barri amb el centre de la ciutat i altes barris.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.965332875130265, -0.17734454333938673],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Totes les edats"
    },
    {
        "nombre": "Plaça carrer Perú amb Jaume II",
        "descripcion": "Espai situat al costat del col·legi Botànic Cavanilles, que compta amb un parc infantil amb ombra i bancs.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Lliure",
        "direccion": [38.96459877927735, -0.17651842284574792],
        "web": null,
        "telefono": null,
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Infància (3-12 anys)"
    },
    {
        "nombre": "Centre de Salut de Corea",
        "descripcion": "Promou junt al ajuntament de Gandia, la iniciativa \"Gandia Camina\", promovent que moltes persones isquen a caminar. Es pot demanar informació sobre els grups, horaris, etc. tant en el centre de salut com a l'ajuntament de Gandia.",
        "modalidad": "Presencial",
        "acceso": "Gratuït",
        "condiciones": "Requereix inscripció",
        "direccion": [38.97494432126984, -0.17803801187419507],
        "web": "https://sanidad.gandia.org/actius-per-a-la-salut-comunitaria/",
        "telefono": "96 295 94 35",
        "email": null,
        "barrio": "Corea",
        "establecimiento": "Sí",
        "finalidad": ["Prevenció", "Promoció"],
        "temas": ["Activitat física"],
        "grupo_de_edad": "Joventut (18-35 anys)"
    }



    // Continuar con el resto de los datos...
]
